name: gazefusion
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip:
      - einops==0.8.0
      - imageio==2.36.1
      - numpy==1.26.3
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.10.0.84
      - pillow==10.2.0
      - protobuf==5.29.2
      - pytorch-lightning==2.5.0.post0
      - pyyaml==6.0.2
      - safetensors==0.4.5
      - scikit-image==0.25.0
      - scipy==1.14.1
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - timm==1.0.12
      - tokenizers==0.21.0
      - torch==2.5.1+cu124
      - torchmetrics==1.6.1
      - torchvision==0.20.1+cu124
      - tqdm==4.67.1
      - transformers==4.47.1
      - typing-extensions==4.9.0
